# Dockerfile.ginweb
FROM golang:1.22-alpine

RUN go env -w GO111MODULE=on \
    && go env -w GOPROXY=https://goproxy.cn,direct

WORKDIR /app

COPY . .

RUN go build -o ginweb main.go

EXPOSE 7070

CMD ["./ginweb", "ginweb"]
